default_language_version:
  python: python3

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
        args: [ "--py39-plus" ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ".txt"
      - id: end-of-file-fixer
        exclude: ".ipynb"
      - id: check-json
      - id: check-yaml
        args: [ '--allow-multiple-documents' ]
      - id: debug-statements
      - id: pretty-format-json
        args: ['--autofix', '--no-ensure-ascii', '--no-sort-keys']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.5.1'
    hooks:
      - id: ruff
        args: [ "--fix" ]

  # https://github.com/python/black#version-control-integration
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black-jupyter

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy

# TODO: Reconsider using the alexjs hook when there is a way to ignore particular warnings and/or files.
#  - repo: "https://github.com/mfisher87/alexjs-pre-commit-mirror"
#    rev: "v11.0.1"  # Use the sha / tag you prefer
#    hooks:
#      - id: "alex"
