ci:
  autoupdate_schedule: "monthly" # Like dependabot
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autoupdate_branch: "develop"
  autofix_prs: false # Comment "pre-commit.ci autofix" on a PR to trigger

default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
        # Validate format
        - id: check-yaml
          args: [ '--allow-multiple-documents' ]
        - id: check-toml
        - id: check-json
          args: ['--autofix', '--no-ensure-ascii', '--no-sort-keys']
        # Check for common mistakes
        - id: check-added-large-files
        - id: check-case-conflict
        # - id: check-illegal-windows-names # TODO: Enable in next release
        - id: check-merge-conflict
        - id: check-executables-have-shebangs
        - id: check-shebang-scripts-are-executable
        - id: check-symlinks
        - id: check-vcs-permalinks
        - id: destroyed-symlinks
        - id: detect-private-key
        - id: end-of-file-fixer
          exclude: ".ipynb"
        - id: mixed-line-ending
        - id: no-commit-to-branch # protects `main` by default
        - id: debug-statements
        - id: trailing-whitespace
          exclude: ".txt"
        
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.2
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
      - id: ruff-format

  # https://github.com/python/black#version-control-integration
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black-jupyter

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy

# TODO: Reconsider using the alexjs hook when there is a way to ignore particular warnings and/or files.
#  - repo: "https://github.com/mfisher87/alexjs-pre-commit-mirror"
#    rev: "v11.0.1"  # Use the sha / tag you prefer
#    hooks:
#      - id: "alex"
